[package]
name = "celeste_map"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.10.1"
reqwest = { version = "0.12.15", features = ["blocking"] }
sdl2 = { version = "0.37.0" }
serde_json = "1.0.140"
