[package]
name = "celeste_map"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.8.0"
reqwest = { version = "0.12.9", features = ["blocking"] }
sdl2 = { version = "0.37.0", features = ["bundled"] }
serde_json = "1.0.133"
